Create Procedure FACTURE_des_EXAMENS_FAITS_par_ID_CONS
@NoCONSULTATION NVARCHAR(50)

AS

SELECT     dbo.CONSULTATION.ID_CONSULTATION, dbo.ASSUREUR.NOM_ASSUREUR AS Assureur, 
                      dbo.SERVICES_RENDUS.DESCRIPTION_SERV_RENDUS AS Traitement, dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER AS [Prix total], 
                      dbo.ASSUREUR.POURCENTAGE * 100 AS [%], dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER * dbo.ASSUREUR.POURCENTAGE AS [Prix Personnel], 
                      dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER - dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER * dbo.ASSUREUR.POURCENTAGE AS [Prix de l'Assureur'],
                       dbo.TRAITEMENT_CONSULTATION.PAYED, dbo.TRAITEMENT_CONSULTATION.RENDU
FROM         dbo.SERVICES_RENDUS INNER JOIN
                      dbo.TARIF_DEL_ASSUREUR ON dbo.SERVICES_RENDUS.ID_SERVICES_RENDUS = dbo.TARIF_DEL_ASSUREUR.ID_SERVICES_RENDUS INNER JOIN
                      dbo.ASSUREUR ON dbo.TARIF_DEL_ASSUREUR.ID_ASSUREUR = dbo.ASSUREUR.ID_ASSUREUR INNER JOIN
                      dbo.CATEG_SERVICES_RENDUS ON 
                      dbo.SERVICES_RENDUS.ID_CATEG_SER_RENDUS = dbo.CATEG_SERVICES_RENDUS.ID_CATEG_SER_RENDUS INNER JOIN
                      dbo.TRAITEMENT_CONSULTATION ON 
                      dbo.SERVICES_RENDUS.ID_SERVICES_RENDUS = dbo.TRAITEMENT_CONSULTATION.ID_SERVICES_RENDUS INNER JOIN
                      dbo.CONSULTATION ON dbo.TRAITEMENT_CONSULTATION.ID_CONSULTATION = dbo.CONSULTATION.ID_CONSULTATION INNER JOIN
                      dbo.PATIENT ON dbo.ASSUREUR.ID_ASSUREUR = dbo.PATIENT.ID_ASSUREUR AND 
                      dbo.CONSULTATION.ID_PATIENT = dbo.PATIENT.ID_PATIENT
WHERE     (dbo.CONSULTATION.ID_CONSULTATION = @NoCONSULTATION) AND (dbo.TRAITEMENT_CONSULTATION.RENDU = 1) AND 
                      (dbo.TRAITEMENT_CONSULTATION.PAYED = 1)