Create Procedure FACTURE_des_TRAITEMENTS_de_SUIVI_FINALE

@ID_CONSULTATION NVARCHAR(50)

AS

SELECT     dbo.HOSPITALISATION.ID_CONSULTATION, dbo.HOSPITALISATION.ID_HOSPITALISATION, dbo.ASSUREUR.NOM_ASSUREUR, 
                      dbo.TRAITEMENT_SUIVIE.ID_SERVICES_RENDUS, dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER AS PRIX_TOTAL, 
                      dbo.ASSUREUR.POURCENTAGE * dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER AS PRIX_du_PATIENT, 
                      dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER - dbo.ASSUREUR.POURCENTAGE * dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER AS PRIX_del_ASSUREUR,
                       dbo.TRAITEMENT_SUIVIE.PAYED, dbo.TRAITEMENT_SUIVIE.RENDU
FROM         dbo.ASSUREUR INNER JOIN
                      dbo.TARIF_DEL_ASSUREUR INNER JOIN
                      dbo.SERVICES_RENDUS ON dbo.TARIF_DEL_ASSUREUR.ID_SERVICES_RENDUS = dbo.SERVICES_RENDUS.ID_SERVICES_RENDUS ON 
                      dbo.ASSUREUR.ID_ASSUREUR = dbo.TARIF_DEL_ASSUREUR.ID_ASSUREUR INNER JOIN
                      dbo.CONSULTATION INNER JOIN
                      dbo.HOSPITALISATION ON dbo.CONSULTATION.ID_CONSULTATION = dbo.HOSPITALISATION.ID_CONSULTATION INNER JOIN
                      dbo.PATIENT ON dbo.CONSULTATION.ID_PATIENT = dbo.PATIENT.ID_PATIENT ON 
                      dbo.ASSUREUR.ID_ASSUREUR = dbo.PATIENT.ID_ASSUREUR INNER JOIN
                      dbo.FICHE_DE_SUIVIE ON dbo.HOSPITALISATION.ID_HOSPITALISATION = dbo.FICHE_DE_SUIVIE.ID_HOSPITALISATION INNER JOIN
                      dbo.TRAITEMENT_SUIVIE ON dbo.SERVICES_RENDUS.ID_SERVICES_RENDUS = dbo.TRAITEMENT_SUIVIE.ID_SERVICES_RENDUS AND 
                      dbo.FICHE_DE_SUIVIE.ID_SUIVIE = dbo.TRAITEMENT_SUIVIE.ID_SUIVIE
WHERE     (dbo.HOSPITALISATION.ID_CONSULTATION = @ID_CONSULTATION) AND (dbo.TRAITEMENT_SUIVIE.PAYED = 1) AND 
                      (dbo.TRAITEMENT_SUIVIE.RENDU = 1)