Create Procedure FACTURE_des_TRAITEMENTS_FAITS_Hosp_PATIENT

@ID_HOSPITALISATION NVARCHAR(50)

AS

SELECT     dbo.PATIENT.NOM + N' ' + dbo.PATIENT.PRENOM AS Noms, dbo.ASSUREUR.NOM_ASSUREUR AS Assureur, 
                      dbo.ASSUREUR.POURCENTAGE * 100 AS [%], dbo.SERVICES_RENDUS.DESCRIPTION_SERV_RENDUS AS Traitements, 
                      dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER AS [Prix total], 
                      dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER - dbo.ASSUREUR.POURCENTAGE * dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER AS [Prix d'assureur'],
                       dbo.ASSUREUR.POURCENTAGE * dbo.TARIF_DEL_ASSUREUR.MAXIMA_A_PAYER AS [Prix du patient]
FROM         dbo.ASSUREUR INNER JOIN
                      dbo.TARIF_DEL_ASSUREUR INNER JOIN
                      dbo.SERVICES_RENDUS ON dbo.TARIF_DEL_ASSUREUR.ID_SERVICES_RENDUS = dbo.SERVICES_RENDUS.ID_SERVICES_RENDUS ON 
                      dbo.ASSUREUR.ID_ASSUREUR = dbo.TARIF_DEL_ASSUREUR.ID_ASSUREUR INNER JOIN
                      dbo.CONSULTATION INNER JOIN
                      dbo.HOSPITALISATION ON dbo.CONSULTATION.ID_CONSULTATION = dbo.HOSPITALISATION.ID_CONSULTATION INNER JOIN
                      dbo.PATIENT ON dbo.CONSULTATION.ID_PATIENT = dbo.PATIENT.ID_PATIENT ON 
                      dbo.ASSUREUR.ID_ASSUREUR = dbo.PATIENT.ID_ASSUREUR INNER JOIN
                      dbo.FICHE_DE_SUIVIE ON dbo.HOSPITALISATION.ID_HOSPITALISATION = dbo.FICHE_DE_SUIVIE.ID_HOSPITALISATION INNER JOIN
                      dbo.TRAITEMENT_SUIVIE ON dbo.SERVICES_RENDUS.ID_SERVICES_RENDUS = dbo.TRAITEMENT_SUIVIE.ID_SERVICES_RENDUS AND 
                      dbo.FICHE_DE_SUIVIE.ID_SUIVIE = dbo.TRAITEMENT_SUIVIE.ID_SUIVIE
WHERE     (dbo.HOSPITALISATION.ID_HOSPITALISATION = @ID_HOSPITALISATION) AND (dbo.TRAITEMENT_SUIVIE.PAYED = 1)