Create Procedure SELECT_DETAILS_des_EXAMS_au_LABO

@ID_CONSULTATION NVARCHAR(50)

AS

SELECT EXAMENS_A_FAIRE.CODE_EXAMEN, RESULTATS_EXAMEN.ID_CONSULTATION, EXAMENS_A_FAIRE.UNITE_DE_MESURE, EXAMENS_A_FAIRE.VALEUR_NORMALE, EXAMENS_A_FAIRE.EXAM_DESCRIPTION 
FROM EXAMENS_A_FAIRE INNER JOIN RESULTATS_EXAMEN ON EXAMENS_A_FAIRE.CODE_EXAMEN = RESULTATS_EXAMEN.CODE_EXAMEN 
WHERE (RESULTATS_EXAMEN.ID_CONSULTATION = @ID_CONSULTATION)