CREATE PROCEDURE INSERT_INTO_CONSULTATION_TABLE

@ID_CONSULTATION	nvarchar(20),
@ID_PATIENT	nvarchar(10)	,
@POIDS	float	,
@DATE_CONSULTATION	datetime	,
@HEURE_CONSULTATION	nvarchar(10)	,
@CODE_PLAINTE	int	,
@OBSERVATIONS	nvarchar(50)	

AS 
INSERT INTO CONSULTATION
VALUES(@ID_CONSULTATION,@ID_PATIENT,@POIDS	,@DATE_CONSULTATION	,
@HEURE_CONSULTATION,@CODE_PLAINTE,@OBSERVATIONS	)