CREATE PROCEDURE INSERT_INTO_PRODUIT_EN_STOCK

@CODE_PRODUIT	nvarchar(10)	,
@IDENTIFIC_PRODUIT	nvarchar(50)	,
@UNITE_DE_MESURE	nvarchar(10)	,
@ID_CATEG_PRODUIT	int

AS
INSERT INTO PRODUIT_EN_STOCK
VALUES(@CODE_PRODUIT	,@IDENTIFIC_PRODUIT	,@UNITE_DE_MESURE,@ID_CATEG_PRODUIT)