CREATE PROCEDURE INSERT_INTO_SERVICES_RENDUS

@ID_SERVICES_RENDUS	nvarchar(10)	,
@DESCRIPTION_SERV_RENDUS	nvarchar(50)	,
@ID_CATEG_SER_RENDUS	int	

AS
INSERT INTO SERVICES_RENDUS
VALUES(@ID_SERVICES_RENDUS,@DESCRIPTION_SERV_RENDUS	,@ID_CATEG_SER_RENDUS)