CREATE PROCEDURE INSERT_INTO_RESULTATS_EXAMEN

@CODE_EXAMEN	nvarchar(10)	,
@ID_SERVICES_RENDUS	nvarchar(10)	,
@ID_CONSULTATION	nvarchar(20)	,
@DATE_EXAMEN	datetime	,
@ID_TYPE_ECHANTILLON	int	,
@RESULTATS	nvarchar(50)	

AS
INSERT INTO RESULTATS_EXAMEN
VALUES(@CODE_EXAMEN,@ID_SERVICES_RENDUS,@ID_CONSULTATION,
@DATE_EXAMEN,@ID_TYPE_ECHANTILLON,@RESULTATS)