CREATE PROCEDURE INSERT_INTO_SERVICE_TABLE

@ID_SERVICE	nvarchar(10)	,
@NOM_SERVICE	nvarchar(50)	,
@ID_CATEG_SERVICE	int	

AS
INSERT INTO SERVICES
VALUES(@ID_SERVICE	,@NOM_SERVICE	,@ID_CATEG_SERVICE)
