CREATE PROCEDURE INSERT_INTO_TRANSFERT_TABLE

@ID_TRANSFERT	nvarchar(10)	,
@ID_CONSULTATION	nvarchar(20)	,
@ID_DESTINATION	int	,
@DATE_TRANSFERT	datetime	,
@HEURE_TRANSFERT	nvarchar(10)	,
@RECOMMANDATIONS	nvarchar(50)	,
@OBSERVATIONS	nvarchar(50)	
		
AS
INSERT INTO TRANSFERT
VALUES(@ID_TRANSFERT,@ID_CONSULTATION	,@ID_DESTINATION,@DATE_TRANSFERT,
@HEURE_TRANSFERT	,@RECOMMANDATIONS	,@OBSERVATIONS)