CREATE PROCEDURE INSERT_INTO_HOSPITALISATION

@ID_HOSPITALISATION	nvarchar(10)	,
@ID_SERVICE	nvarchar(10)	,
@No_CHAMBRE	nvarchar(10)	,
@ID_CONSULTATION	nvarchar(20)	,
@DATE_D_ENTREE	datetime	,
@HEURE_D_ENTREE	nvarchar(10)	

AS
INSERT INTO HOSPITALISATION
VALUES(@ID_HOSPITALISATION,@ID_SERVICE,@No_CHAMBRE,@ID_CONSULTATION	,
@DATE_D_ENTREE,@HEURE_D_ENTREE)