CREATE PROCEDURE INSERT_INTO_PERSONNEL_DE_GARDE

@ID_PERSONNEL	nvarchar(10)	,
@NOM	kamonyo_name,
@PRENOM	kamonyo_name,
@AUTRE_NOM	kamonyo_name,
@SEXE	char(1)	,
@ID_CATEG_PERSONNEL	int	

AS 
INSERT INTO PERSONNEL_DE_GARDE
VALUES(@ID_PERSONNEL	,@NOM,@PRENOM	,@AUTRE_NOM,@SEXE	,@ID_CATEG_PERSONNEL)