CREATE PROCEDURE INSERT_INTO_RESULTATS_EXAMS_HOSPITALISATION

@CODE_EXAMEN	nvarchar(10)	,
@ID_SUIVI INT
AS

INSERT INTO RESULTATS_EXAM_HOSPITALISATION(CODE_EXAMEN,ID_SUIVI,
ID_TYPE_ECHANTILLON,RESULTATS,DEJA_EXAMINE,PAYES)
VALUES(@CODE_EXAMEN,@ID_SUIVI,NULL,'',0,0)
