CREATE PROCEDURE UPDATE_PATIENT_TABLE

@ID_PATIENT	nvarchar(10)	,
@NOM	nvarchar(50)	,
@PRENOM	nvarchar(50)	,
@AUTRE_NOM	nvarchar(50)	,
@ID_ASSUREUR	nvarchar(10)	,
@PROFESSION	nvarchar(20)	,
@SEXE	char(1)	,
@DATE_NAISSANCE	datetime	,
@No_CARTE_IDENTITE	nvarchar(10)	,
@RELIGION	nvarchar(10)	,
@MARITAL_STATUS	nvarchar(10)	,
@CONJOINT	nvarchar(50)	,
@MOBILE_PHONE	nvarchar(20)	,
@HOME_PHONE	nvarchar(10)	,
@RESIDENCE	nvarchar(50)	,
@No_CARTE_ASSUREUR	nvarchar(20)	,
@ID_CATEGORY_PATIENT	int	,
@NATIONALITY	nvarchar(20)	,
@PROVINCE	nvarchar(20)	,
@DISTRICT	nvarchar(20)	

AS
UPDATE PATIENT
SET NOM=@NOM,
PRENOM=@PRENOM,
AUTRE_NOM=@AUTRE_NOM,
ID_ASSUREUR=@ID_ASSUREUR,
PROFESSION=@PROFESSION,
No_CARTE_IDENTITE=@No_CARTE_IDENTITE,
RELIGION=@RELIGION,
MARITAL_STATUS=@MARITAL_STATUS,
CONJOINT=@CONJOINT,
MOBILE_PHONE=@MOBILE_PHONE,
HOME_PHONE=@HOME_PHONE,
RESIDENCE=@RESIDENCE,
No_CARTE_ASSUREUR=@No_CARTE_ASSUREUR,
ID_CATEGORY_PATIENT=@ID_CATEGORY_PATIENT,
NATIONALITY=@NATIONALITY,
PROVINCE=@PROVINCE,
DISTRICT=@DISTRICT
WHERE ID_PATIENT=@ID_PATIENT
