CREATE PROCEDURE UPDATE_CATEGORY_PATIENT

@ID_CATEGORY_PATIENT	int	,
@DESCRIPTION_PATIENT	nvarchar(50)	

AS
UPDATE CATEGORY_PATIENT
SET DESCRIPTION_PATIENT=@DESCRIPTION_PATIENT
WHERE ID_CATEGORY_PATIENT=@ID_CATEGORY_PATIENT