CREATE PROCEDURE UPDATE_LA_GARDE

@No_LA_GARDE	int	,
@ID_PERSONNEL	nvarchar(10)	,
@ID_SERVICE	nvarchar(10)	,
@DATE_GARDE_DEBUT	datetime	,
@HEURE_DEBUT	nvarchar(10)	,
@DATE_GARDE_FIN	datetime	,
@HEURE_FIN	nvarchar(10)	

AS
UPDATE LA_GARDE
SET ID_PERSONNEL=@ID_PERSONNEL,
ID_SERVICE=@ID_SERVICE,
DATE_GARDE_DEBUT=@DATE_GARDE_DEBUT,
HEURE_DEBUT=@HEURE_DEBUT,
DATE_GARDE_FIN=@DATE_GARDE_FIN,
HEURE_FIN=@HEURE_FIN
WHERE No_LA_GARDE=@No_LA_GARDE