CREATE PROCEDURE UPDATE_EXAMENS_A_FAIRE

@CODE_EXAMEN	nvarchar(10)	,
@ID_SERVICES_RENDUS	nvarchar(10)	,
@EXAM_DESCRIPTION	nvarchar(50)	,
@ID_DEPART_LABO	int	,
@UNITE_DE_MESURE	nvarchar(5)	,
@VALEUR_NORMALE	float	

AS
UPDATE EXAMENS_A_FAIRE
SET EXAM_DESCRIPTION=@EXAM_DESCRIPTION,
ID_DEPART_LABO=@ID_DEPART_LABO,
UNITE_DE_MESURE=@UNITE_DE_MESURE,
VALEUR_NORMALE=@VALEUR_NORMALE
WHERE CODE_EXAMEN=@CODE_EXAMEN AND ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS