CREATE PROCEDURE UPDATE_TRAITEMENT_SUIVIE

@No_TRAITEMENT_SUIVIE	int	,
@ID_SUIVIE	int	,
@ID_SERVICES_RENDUS	nvarchar(10)	

AS
UPDATE TRAITEMENT_SUIVIE
SET ID_SUIVIE=@ID_SUIVIE,
ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS
WHERE No_TRAITEMENT_SUIVIE=@No_TRAITEMENT_SUIVIE