CREATE PROCEDURE UPDATE_RESULTATS_EXAMEN

@CODE_EXAMEN	nvarchar(10)	,
@ID_SERVICES_RENDUS	nvarchar(10)	,
@ID_CONSULTATION	nvarchar(20)	,
@DATE_EXAMEN	datetime	,
@ID_TYPE_ECHANTILLON	int	,
@RESULTATS	nvarchar(50)	

AS
UPDATE RESULTATS_EXAMEN
SET ID_CONSULTATION=@ID_CONSULTATION,
DATE_EXAMEN=@DATE_EXAMEN,
ID_TYPE_ECHANTILLON=@ID_TYPE_ECHANTILLON,
RESULTATS=@RESULTATS
WHERE CODE_EXAMEN=@CODE_EXAMEN AND ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS