CREATE PROCEDURE UPDATE_FICHE_DE_SUIVIE

@ID_SUIVIE	int	,
@ID_HOSPITALISATION	nvarchar(10)	,
@DATE_SUIVIE	datetime	,
@HEURE_SUIVIE	nvarchar(10)	,
@ID_SIGNES_VITAUX	int	,
@OBSERVATIONS	nvarchar(50)	

AS
UPDATE FICHE_DE_SUIVIE
SET ID_HOSPITALISATION=@ID_HOSPITALISATION,
DATE_SUIVIE=@DATE_SUIVIE,
HEURE_SUIVIE=@HEURE_SUIVIE,
ID_SIGNES_VITAUX=@ID_SIGNES_VITAUX,
OBSERVATIONS=@OBSERVATIONS
WHERE ID_SUIVIE=@ID_SUIVIE