CREATE PROCEDURE UPDATE_SERVICES_TABLE

@ID_SERVICE	nvarchar(10)	,
@NOM_SERVICE	nvarchar(50)	,
@ID_CATEG_SERVICE	int

AS
UPDATE SERVICES
SET NOM_SERVICE=@NOM_SERVICE,
ID_CATEG_SERVICE=@ID_CATEG_SERVICE
WHERE ID_SERVICE=@ID_SERVICE