CREATE PROCEDURE UPDATE_SERVICES_RENDUS

@ID_SERVICES_RENDUS	nvarchar(10)	,
@DESCRIPTION_SERV_RENDUS	nvarchar(50)	,
@ID_CATEG_SER_RENDUS	int	

AS
UPDATE SERVICES_RENDUS
SET DESCRIPTION_SERV_RENDUS=@DESCRIPTION_SERV_RENDUS,
ID_CATEG_SER_RENDUS=@ID_CATEG_SER_RENDUS
WHERE ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS