CREATE PROCEDURE UPDATE_CATEG_PERSONNEL

@ID_CATEG_PERSONNEL	int	,
@CATEG_IDENTIFICATION	kamonyo_name

AS
UPDATE CATEG_PERSONNEL
SET CATEG_IDENTIFICATION=@CATEG_IDENTIFICATION
WHERE ID_CATEG_PERSONNEL=@ID_CATEG_PERSONNEL