CREATE PROCEDURE UPDATE_DESTINATION_TRANSFERT

@ID_DESTINATION	int	,
@NOM_DESTINATION	nvarchar(20)	

AS
UPDATE DESTINATION_TRANSFERT
SET NOM_DESTINATION=@NOM_DESTINATION
WHERE ID_DESTINATION=@ID_DESTINATION