CREATE PROCEDURE UPDATE_ENTREE_EN_STOCK

@No_REFERENCE	int	,
@ID_STOCK	nvarchar(10)	,
@CODE_PRODUIT	nvarchar(10)	,
@DATE_D_ENTREE	datetime	,
@HEURE_D_ENTREE	nvarchar(10)	,
@QUANTITE_ENTREE	float	,
@PRIX_UNITAIRE	money	,
@DATE_EXPIRATION	datetime	,
@ID_STOCK_SOURCE	nvarchar(10)	

AS 
UPDATE ENTREE_EN_STOCK
SET ID_STOCK=@ID_STOCK,
CODE_PRODUIT=@CODE_PRODUIT,
DATE_D_ENTREE=@DATE_D_ENTREE,
HEURE_D_ENTREE=@HEURE_D_ENTREE,
QUANTITE_ENTREE=@QUANTITE_ENTREE,
PRIX_UNITAIRE=@PRIX_UNITAIRE,
DATE_EXPIRATION=@DATE_EXPIRATION,
ID_STOCK_SOURCE=@ID_STOCK_SOURCE
WHERE No_REFERENCE=@No_REFERENCE