CREATE PROCEDURE UPDATE_UTILISATEURS_TABLE

@LOGIN_NAME	nvarchar(20)	,
@PASSWORD	nvarchar(20)	,
@ID_SPECIALISATION	int	,
@NOM	nvarchar(50)	,
@PRENOM	nvarchar(50)	,
@SEXE	char(1)	,
@ID_SERVICE	nvarchar(10)	

AS
UPDATE UTILISATEURS
SET PASSWORD=@PASSWORD,
ID_SPECIALISATION=@ID_SPECIALISATION,
NOM=@NOM,
PRENOM=@PRENOM,
ID_SERVICE=@ID_SERVICE
WHERE LOGIN_NAME=@LOGIN_NAME