CREATE PROCEDURE UPDATE_TARIF_DEL_ASSUREUR

@ID_TARIF_ASSUREUR	int	,
@ID_ASSUREUR	nvarchar(10)	,
@ID_SERVICES_RENDUS	nvarchar(10)	,
@MAXIMA_A_PAYER	money	

AS
UPDATE TARIF_DEL_ASSUREUR
SET ID_ASSUREUR=@ID_ASSUREUR,
ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS,
MAXIMA_A_PAYER=@MAXIMA_A_PAYER
WHERE ID_TARIF_ASSUREUR=@ID_TARIF_ASSUREUR