CREATE PROCEDURE UPDATE_TYPE_D_ECHANTILLON

@ID_TYPE_ECHANTILLON	int	,
@TYPE_D_ECHANTILLON	nvarchar(20)	

AS
UPDATE TYPE_D_ECHANTILLON
SET TYPE_D_ECHANTILLON=@TYPE_D_ECHANTILLON
WHERE ID_TYPE_ECHANTILLON=@ID_TYPE_ECHANTILLON