CREATE PROCEDURE UPDATE_ASSUREUR_TABLE

@ID_ASSUREUR	nvarchar(10)	,
@NOM_ASSUREUR	nvarchar(50)	,
@POURCENTAGE	float

AS 
UPDATE ASSUREUR 
SET NOM_ASSUREUR=@NOM_ASSUREUR,
POURCENTAGE=@POURCENTAGE
WHERE ID_ASSUREUR=@ID_ASSUREUR