CREATE PROCEDURE UPDATE_SORTIE_DE_STOCK

@No_REFERENCE	int	,
@ID_STOCK	nvarchar(10)	,
@CODE_PRODUIT	nvarchar(10)	,
@DATE_DE_SORTIE	datetime	,
@HEURE_DE_SORTIE	nvarchar(10)	,
@QUANTITE_SORTIE	float	,
@DATE_EXPIRE	datetime

AS
UPDATE SORTIE_DE_STOCK
SET ID_STOCK=@ID_STOCK,
CODE_PRODUIT=@CODE_PRODUIT,
DATE_DE_SORTIE=@DATE_DE_SORTIE,
HEURE_DE_SORTIE=@HEURE_DE_SORTIE,
QUANTITE_SORTIE=@QUANTITE_SORTIE,
DATE_EXPIRE=@DATE_EXPIRE
WHERE No_REFERENCE=@No_REFERENCE