CREATE PROCEDURE UPDATE_RESULTATS_EXAMS_HOSPITALISATION

@CODE_EXAMEN	nvarchar(10)	,
@ID_SUIVI INT,
@ID_TYPE_ECHANTILLON	int	,
@RESULTATS	nvarchar(50)	

AS
UPDATE RESULTATS_EXAMS_HOSPITALISATION
SET ID_TYPE_ECHANTILLON=@ID_TYPE_ECHANTILLON,
RESULTATS=@RESULTATS,DEJA_EXAMINE=1
WHERE CODE_EXAMEN=@CODE_EXAMEN AND ID_SUIVI=@ID_SUIVI
