CREATE PROCEDURE UPDATE_STOCK_TABLE

@ID_STOCK	nvarchar(10)	,
@ID_SERVICE	nvarchar(10)	,
@NAME_STOCK	nvarchar(20)	

AS
UPDATE STOCK
SET ID_SERVICE=@ID_SERVICE,
NAME_STOCK=@NAME_STOCK
WHERE ID_STOCK=@ID_STOCK