CREATE PROCEDURE UPDATE_TRAITEMENT_CONSULTATION

@No_TRAITEMENT_CONS	int	,
@ID_CONSULTATION	nvarchar(20)	,
@ID_SERVICES_RENDUS	nvarchar(10)	

AS
UPDATE TRAITEMENT_CONSULTATION
SET ID_CONSULTATION=@ID_CONSULTATION,
ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS
WHERE No_TRAITEMENT_CONS=@No_TRAITEMENT_CONS