Create PROCEDURE [dbo].[UPDATE_RESULTAT_EXAMEN_SET_IT_NotYet_examinated]

@ID_CONSULTATION NVARCHAR(50),
@CODE_EXAMEN NVARCHAR(20)

AS

--DECLARE @CODE_EXAM NVARCHAR(20)
--
--SET @CODE_EXAM=(SELECT     dbo.RESULTATS_EXAMEN.CODE_EXAMEN
--				FROM         dbo.RESULTATS_EXAMEN INNER JOIN
--								dbo.EXAMENS_A_FAIRE ON dbo.RESULTATS_EXAMEN.CODE_EXAMEN = dbo.EXAMENS_A_FAIRE.CODE_EXAMEN
--				WHERE     (dbo.RESULTATS_EXAMEN.ID_CONSULTATION = @ID_CONSULTATION) 
--						AND (dbo.RESULTATS_EXAMEN.DEJA_EXAMINE = 0) 
--						AND (dbo.RESULTATS_EXAMEN.PAYES = 0) 
--						AND (dbo.EXAMENS_A_FAIRE.EXAM_DESCRIPTION = @CODE_EXAMEN))
-----------------------------------------------------------------------------------

UPDATE RESULTATS_EXAMEN
SET DEJA_EXAMINE=0
WHERE CODE_EXAMEN=@CODE_EXAMEN AND ID_CONSULTATION=@ID_CONSULTATION