CREATE PROCEDURE UPDATE_CATEGORY_SERVICE

@ID_CATEG_SERVICE	int	,
@NOM_CATEG_SERVICE	nvarchar(20)	

AS
UPDATE CATEGORY_SERVICE
SET NOM_CATEG_SERVICE=@NOM_CATEG_SERVICE
WHERE ID_CATEG_SERVICE=@ID_CATEG_SERVICE