CREATE PROCEDURE UPDATE_PLAINTES_TABLE

@CODE_PLAINTE	int	,
@DESCRIPTION_PLAINTE	nvarchar(50)	

AS
UPDATE PLAINTES
SET DESCRIPTION_PLAINTE=@DESCRIPTION_PLAINTE
WHERE CODE_PLAINTE=@CODE_PLAINTE