CREATE PROCEDURE UPDATE_SPECIALISATION_TABLE

@ID_SPECIALISATION	int	,
@SPECIALITE	nvarchar(50)	,
@ID_CATEG_UTILISATEUR	int	
		
AS
UPDATE SPECIALISATION
SET SPECIALITE=@SPECIALITE,
ID_CATEG_UTILISATEUR=@ID_CATEG_UTILISATEUR
WHERE ID_SPECIALISATION=@ID_SPECIALISATION