CREATE PROCEDURE UPDATE_PRODUIT_EN_STOCK

@CODE_PRODUIT	nvarchar(10)	,
@IDENTIFIC_PRODUIT	nvarchar(50)	,
@UNITE_DE_MESURE	nvarchar(10)	,
@ID_CATEG_PRODUIT	int	

AS
UPDATE PRODUIT_EN_STOCK
SET IDENTIFIC_PRODUIT=@IDENTIFIC_PRODUIT,
UNITE_DE_MESURE=@UNITE_DE_MESURE,
ID_CATEG_PRODUIT=@ID_CATEG_PRODUIT
WHERE CODE_PRODUIT=@CODE_PRODUIT