CREATE PROCEDURE UPDATE_PERSONNEL_DE_GARDE

@ID_PERSONNEL	nvarchar(10)	,
@NOM	kamonyo_name,
@PRENOM	kamonyo_name,
@AUTRE_NOM	kamonyo_name,
@SEXE	char(1)	,
@ID_CATEG_PERSONNEL	int	

AS
UPDATE PERSONNEL_DE_GARDE
SET NOM=@NOM,
PRENOM=@PRENOM,
AUTRE_NOM=@AUTRE_NOM,
ID_CATEG_PERSONNEL=@ID_CATEG_PERSONNEL
WHERE ID_PERSONNEL=@ID_PERSONNEL