CREATE PROCEDURE UPDATE_CATEGORY_UTILISATEUR

@ID_CATEG_UTILISATEUR	int	,
@DESCRIPTION_USER_CATEG	nvarchar(20)	

AS
UPDATE CATEGORY_UTILISATEUR
SET DESCRIPTION_USER_CATEG=@DESCRIPTION_USER_CATEG
WHERE ID_CATEG_UTILISATEUR=@ID_CATEG_UTILISATEUR