Create Procedure UPDATE_TRAITEMENT_SUIVI_SET_IT_AS_PAYE

@ID_HOSPITALISATION NVARCHAR(20),
@NOM_TRAITEMENT NVARCHAR(50)

AS

DECLARE @CODE_TRAITEMENT NVARCHAR(20)

SET @CODE_TRAITEMENT=(SELECT     dbo.TRAITEMENT_SUIVIE.ID_SERVICES_RENDUS
FROM         dbo.FICHE_DE_SUIVIE INNER JOIN
                      dbo.HOSPITALISATION ON dbo.FICHE_DE_SUIVIE.ID_HOSPITALISATION = dbo.HOSPITALISATION.ID_HOSPITALISATION INNER JOIN
                      dbo.TRAITEMENT_SUIVIE ON dbo.FICHE_DE_SUIVIE.ID_SUIVIE = dbo.TRAITEMENT_SUIVIE.ID_SUIVIE INNER JOIN
                      dbo.SERVICES_RENDUS ON dbo.TRAITEMENT_SUIVIE.ID_SERVICES_RENDUS = dbo.SERVICES_RENDUS.ID_SERVICES_RENDUS
WHERE     (dbo.FICHE_DE_SUIVIE.ID_HOSPITALISATION = @ID_HOSPITALISATION) AND (dbo.TRAITEMENT_SUIVIE.PAYED = 0) AND 
                      (dbo.TRAITEMENT_SUIVIE.RENDU = 0) AND (dbo.SERVICES_RENDUS.DESCRIPTION_SERV_RENDUS =@NOM_TRAITEMENT ))
------------------------------------------------------------------------------------------------------------------

DECLARE @NoSUIVI INT

SET @NoSUIVI=(SELECT     dbo.TRAITEMENT_SUIVIE.ID_SUIVIE
FROM         dbo.FICHE_DE_SUIVIE INNER JOIN
                      dbo.HOSPITALISATION ON dbo.FICHE_DE_SUIVIE.ID_HOSPITALISATION = dbo.HOSPITALISATION.ID_HOSPITALISATION INNER JOIN
                      dbo.TRAITEMENT_SUIVIE ON dbo.FICHE_DE_SUIVIE.ID_SUIVIE = dbo.TRAITEMENT_SUIVIE.ID_SUIVIE INNER JOIN
                      dbo.SERVICES_RENDUS ON dbo.TRAITEMENT_SUIVIE.ID_SERVICES_RENDUS = dbo.SERVICES_RENDUS.ID_SERVICES_RENDUS
WHERE     (dbo.FICHE_DE_SUIVIE.ID_HOSPITALISATION = @ID_HOSPITALISATION) AND (dbo.TRAITEMENT_SUIVIE.PAYED = 0) AND 
                      (dbo.TRAITEMENT_SUIVIE.RENDU = 0) AND (dbo.SERVICES_RENDUS.DESCRIPTION_SERV_RENDUS = @NOM_TRAITEMENT))

-------------------------------------------------------------------------------------------------------------------

UPDATE TRAITEMENT_SUIVIE
SET PAYED=1
WHERE TRAITEMENT_SUIVIE.ID_SERVICES_RENDUS=@CODE_TRAITEMENT AND
		TRAITEMENT_SUIVIE.ID_SUIVIE=@NoSUIVI
