Create Procedure UPDATE_CONSULTATION_POUR_INSERER_A_NOUVEAU

@ID_CONSULTATION NVARCHAR(50),
@POIDS	float,
@OBSERVATIONS	nvarchar(50)

AS

--------------- METTRE LA DATE DU SYSTEME ----------------------
DECLARE @DATE_CONS DATETIME
DECLARE @STRING_DATE_CONS NVARCHAR(20)
DECLARE @HEURE_CONS NVARCHAR(10)

SET @DATE_CONS=GETDATE();
SET @STRING_DATE_CONS=@DATE_CONS;
SET @HEURE_CONS=SUBSTRING(@STRING_DATE_CONS,12,11);

----------------UPDATE CONSULTATION ---------------------------
UPDATE CONSULTATION
SET POIDS=@POIDS,
DATE_CONSULTATION=@DATE_CONS,
HEURE_CONSULTATION=@HEURE_CONS,
OBSERVATIONS=@OBSERVATIONS

WHERE ID_CONSULTATION=@ID_CONSULTATION

-------------------UPDATE RENDEZ-VOUS DE CONSULTATION -------------------------
UPDATE RENDEZ_VOUS_CONSULTATION
SET RENDEZ_VOUS_CONSULTATION.DEJA_CONSULTE=1
WHERE RENDEZ_VOUS_CONSULTATION.ID_CONSULTATION=@ID_CONSULTATION

------------------- UPDATE TRAITEMENT DE CONSULTATION -------------------------
