CREATE PROCEDURE DELETE_TYPE_D_ECHANTILLON

@ID_TYPE_ECHANTILLON	int	,
@TYPE_D_ECHANTILLON	nvarchar(20)	

AS
DELETE TYPE_D_ECHANTILLON
WHERE ID_TYPE_ECHANTILLON=@ID_TYPE_ECHANTILLON AND TYPE_D_ECHANTILLON=@TYPE_D_ECHANTILLON