CREATE PROCEDURE DELETE_CATEGORY_UTILISATEUR

@ID_CATEG_UTILISATEUR	int	,
@DESCRIPTION_USER_CATEG	nvarchar(20)	

AS
DELETE CATEGORY_UTILISATEUR
WHERE ID_CATEG_UTILISATEUR=@ID_CATEG_UTILISATEUR AND DESCRIPTION_USER_CATEG=@DESCRIPTION_USER_CATEG