CREATE PROCEDURE DELETE_TRAITEMENT_SUIVIE

@No_TRAITEMENT_SUIVIE	int,
@ID_SERVICES_RENDUS	nvarchar(10)

AS
DELETE TRAITEMENT_SUIVIE
WHERE No_TRAITEMENT_SUIVIE=@No_TRAITEMENT_SUIVIE AND ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS