CREATE PROCEDURE DELETE_CATEGORY_PRODUIT

@ID_CATEG_PRODUIT	int	,
@DESCRIPTION_CATEGORY	nvarchar(50)	

AS 
DELETE CATEGORY_PRODUIT
WHERE ID_CATEG_PRODUIT=@ID_CATEG_PRODUIT AND DESCRIPTION_CATEGORY=@DESCRIPTION_CATEGORY