CREATE PROCEDURE DELETE_DESTINATION_TRANSFERT

@ID_DESTINATION	int	,
@NOM_DESTINATION	nvarchar(20)	

AS
DELETE DESTINATION_TRANSFERT
WHERE ID_DESTINATION=@ID_DESTINATION AND NOM_DESTINATION=@NOM_DESTINATION