CREATE PROCEDURE DELETE_RESULTATS_EXAMEN

@CODE_EXAMEN	nvarchar(10)	,
@ID_SERVICES_RENDUS	nvarchar(10)	
AS
DELETE RESULTATS_EXAMEN
WHERE CODE_EXAMEN=@CODE_EXAMEN AND ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS