CREATE PROCEDURE DELETE_RENDEZ_VOUS_CONSULTATION

@ID_RENDEZ_VOUS	int	,
@DATE_RENDEZ_VOUS	datetime

AS
DELETE RENDEZ_VOUS_CONSULTATION
WHERE ID_RENDEZ_VOUS=@ID_RENDEZ_VOUS AND DATE_RENDEZ_VOUS=@DATE_RENDEZ_VOUS