CREATE PROCEDURE DELETE_CATEGORY_PATIENT

@ID_CATEGORY_PATIENT	int	,
@DESCRIPTION_PATIENT	nvarchar(50)	

AS
DELETE CATEGORY_PATIENT
WHERE ID_CATEGORY_PATIENT=@ID_CATEGORY_PATIENT AND DESCRIPTION_PATIENT=@DESCRIPTION_PATIENT