CREATE PROCEDURE DELETE_PRODUIT_EN_STOCK

@CODE_PRODUIT	nvarchar(10)	,
@IDENTIFIC_PRODUIT	nvarchar(50)	

AS
DELETE PRODUIT_EN_STOCK
WHERE CODE_PRODUIT=@CODE_PRODUIT AND IDENTIFIC_PRODUIT=@IDENTIFIC_PRODUIT