CREATE PROCEDURE DELETE_TRAITEMENT_CONSULTATION

@No_TRAITEMENT_CONS	int,
@ID_SERVICES_RENDUS	nvarchar

AS
DELETE TRAITEMENT_CONSULTATION
WHERE No_TRAITEMENT_CONS=@No_TRAITEMENT_CONS AND ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS