CREATE PROCEDURE DELETE_EXAMENS_A_FAIRE

@CODE_EXAMEN	nvarchar(10)	,
@ID_SERVICES_RENDUS	nvarchar(10)

AS
DELETE EXAMENS_A_FAIRE
WHERE CODE_EXAMEN=@CODE_EXAMEN AND ID_SERVICES_RENDUS=@ID_SERVICES_RENDUS