CREATE PROCEDURE DELETE_CATEG_PERSONNEL

@ID_CATEG_PERSONNEL	int	,
@CATEG_IDENTIFICATION	kamonyo_name

AS
DELETE CATEG_PERSONNEL
WHERE ID_CATEG_PERSONNEL=@ID_CATEG_PERSONNEL AND CATEG_IDENTIFICATION=@CATEG_IDENTIFICATION