CREATE PROCEDURE DELETE_CATEGORY_SERVICE

@ID_CATEG_SERVICE	int	,
@NOM_CATEG_SERVICE	nvarchar(20)	

AS
DELETE CATEGORY_SERVICE
WHERE ID_CATEG_SERVICE=@ID_CATEG_SERVICE AND NOM_CATEG_SERVICE=@NOM_CATEG_SERVICE